[package]
name = "aiffplay"
version = "0.1.0"
authors = ["Delta-Psi <delta.psi00@gmail.com>"]
edition = "2018"

[dependencies]
aiff = { path = "../aiff" }
cpal = "0.13.1"

[dependencies.dasp]
version = "0.11.0"
features = ["signal", "interpolate", "interpolate-linear"]
