[package]
name = "m64play"
version = "0.1.0"
authors = ["Delta-Psi <delta.psi00@gmail.com>"]
edition = "2018"

[dependencies]
m64 = { path = "../m64" }
bitflags = "1.2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
